pipeline:
  name: remotepipeline
  identifier: remotepipeline
  projectIdentifier: thomas_kouhsari
  orgIdentifier: December_2023
  tags: {}
  stages:
    - stage:
        name: custom
        identifier: custom
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "hi4"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  name: template
                  identifier: template
                  template:
                    templateRef: steptemplate
                    versionLabel: v1
        tags: {}
